### PR TITLE
add fedjeosen NV

### LINKED ISSUE #7: New SFY buoy in Fedjeosen (not yet in Frost)
Ref.: #6 

Will contact again when available.

### PR DESCRIPTION
**Pull request by gauteh**
Fixes #7.

### CODE REVIEW

**Comment by gauteh** [comment]
Her er ein URL som funker: https://frost-beta.met.no/api/v1/obs/met.no/filter/get?incobs=true&time=latest&elementids=%2Awave%2A&stationids=52520 det funker ikkje med printobs ellers endå.

**Comment by bohlinger** [comment]
This works now on my laptop, can you check and complete the merge request? Remember to use 
typeids: 538 instead of 38.

**Comment by gauteh** [comment]
Yes, now 538 works! Great! Ready to merge.

**Comment by bohlinger** [comment]
Merged it, Thanks for the push!

**Pull request merged**
